/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rango_tool_opencvdemo_MainActivity */

#ifndef _Included_com_rango_tool_opencvdemo_MainActivity
#define _Included_com_rango_tool_opencvdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rango_tool_opencvdemo_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rango_tool_opencvdemo_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_rango_tool_opencvdemo_MainActivity
 * Method:    getEdge
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_rango_tool_opencvdemo_MainActivity_getEdge
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
